#ifndef	_RESOURCE_H
#define	_RESOURCE_H

//menu control id 
#define IDM_FILE_NEW	1000
#define IDM_FILE_OPEN	2000
#define IDM_FILE_SAVE	3000
#define IDM_FILE_QUIT	4000
#define IDM_FILE_CLOSE	5000
#define IDM_EDIT_CLEAR_RECV	6000
#define IDM_EDIT_CLEAR_HEX	7000


//button control id 
#define	IDC_GROUP_LEFT		100
#define	IDC_GROUP_LEFT_1	101
#define	IDC_GROUP_BOTTON	102
#define	IDC_EDIT_VIEW		103
#define	IDC_EDIT_VECTOR0	104
#define	IDC_EDIT_VECTOR1	105
#define	IDC_EDIT_VECTOR2	106

#define	IDC_BUTTON_OPENHEX	110
#define	IDC_COMBOBOX_SERIAL	111
#define	IDC_BUTTON_OPENCOM	112
#define	IDC_COMBOBOX_EEPROM	113
#define	IDC_COMBOBOX_BAUD	114
#define	IDC_COMBOBOX_CHECK	115
#define	IDC_COMBOBOX_STOP	116
#define	IDC_BUTTON_CLOSECOM	117 

#define	IDC_BUTTON_DOWNLOAD	130
#define	IDC_BUTTON_UPDATA	131
#define	IDC_BUTTON_TEST		132
#define	IDC_SCROLL_RWT		133
#define	IDC_EDIT_RWV		134


#endif
